### ISSUE TITLE
Potential security issue

### ISSUE THREAD

**Issue by ghost** [nicolaigrv/ForceBattle-old#1]
https://github.com/Fameless9/ForceBattle/blob/e90c8440b8720dab89f9c205e25e3aa0abcda482/src/main/java/net/fameless/forcebattle/command/ResultCommand.java#L168
Checking event.getView().getTitle() to see whether your custom inventory is being used is unsafe, as renaming a chest in an anvil allows users to set their own inventory titles. The correct way to check if your custom inventory is involved with an event is by using custom holders, see here: https://docs.papermc.io/paper/dev/custom-inventory-holder

**Comment by nicolaigrv** [comment]
Hi, I'm aware if that issue. It will definitely be fixed soon.

**Comment by nicolaigrv** [comment]
Fixed in 1.0.2: https://github.com/Fameless9/ForceBattle/releases/tag/1.0.2
